src/main/java/com/kawauso/base/bean/Order.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kawauso.base.bean;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.Transient;
import org.hibernate.annotations.FetchMode;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.Formula;

/**
 *
 * @author chris.weaver
 * 
 * @todo; not all parameters marked transient will remain transient. This was done
 * just to get the class working quickly for both hibernate and sxapi
 */
@Entity
@Table(name = "nxt_oeeh")
public class Order implements Serializable
{
    @Id
    @Column(name = "id", insertable = false, updatable = false)
    private String id;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "order")
    private List<OrderLine> orderLines;
    
    @Column(name = "cono")
    private int cono;

    @Column(name = "custno", insertable = false, updatable = false)
    private BigDecimal custNo;        
    
    @Column(name = "orderno")
    private int orderNo;
    
    @Column(name = "ordersuf")
    private int orderSuf;
    
    @Column(name = "transtype")
    private String transType;
    
    @Column(name = "shipto")
    private String shipTo;
    
    @Column(name = "custpo")
    private String custPo;  
    
//    @Formula("row_number() OVER ( ORDER BY oeeh.orderno ASC)")
//    private int rowNum;
//    
//    @Formula("Count(*) OVER()")
//    private int rowCount;
    
    /** more **/
    
    @Column(name = "enterdt")
    @Temporal(javax.persistence.TemporalType.DATE)
    private Date enterDt;
    
    @Column(name = "invoicedt")
    @Temporal(javax.persistence.TemporalType.DATE)
    private Date invoiceDt;

    @Column(name = "reqshipdt")
    @Temporal(javax.persistence.TemporalType.DATE)
    private Date reqShipDt;

    @Transient
    private Date dueDt;
    
    @Column(name = "totordamt")
    private BigDecimal totalOrderAmt;
              
    @Column(name = "stagecd")
    private int stageCode;

    @Column(name = "whse")
    private String whse;
    
    @Column(name = "shipviaty")
    private String shipVia;
    
    @Column(name = "refer")
    private String reference;
    
    @Column(name = "shipinstr")
    private String instructions;
    
    @Column(name = "termstype")
    private String termsDesc;
    
    @Transient private String soldToName;
    @Transient private String soldToAddr1;
    @Transient private String soldToAddr2;
    @Transient private String soldToCity;
    @Transient private String soldToState;
    @Transient private String soldToZip;
    
    @Column(name = "shiptonm")
    private String shipToName;
    
    @Transient
    private String shipToAddr1;
    
    @Transient
    private String shipToAddr2;
    
    @Transient
    private String shipToCity;
    
    @Transient
    private String shipToState;
    
    @Transient
    private String shipToZip;
    
    @Transient
    private Date shipDt;
    
    @Column(name = "totinvord")
    private BigDecimal subTotal;
    
    @Column(name = "taxamt_1")
    private BigDecimal taxamt_1;
    
    //@Formula("taxamt_1 + 10") //<-- nullpointer?
    @Transient
    private BigDecimal taxAmount;
    
    @Column(name = "totinvamt")
    private BigDecimal invAmount;
    
    //@OneToMany(fetch = FetchType.LAZY)
    //@JoinTable(name = "nxt_oeel", 
    //           joinColumns = {@JoinColumn(name="cono"), @JoinColumn(name="orderno"), @JoinColumn(name="ordersuf")},
    //           inverseJoinColumns = {@JoinColumn(name="cono"), @JoinColumn(name="orderno"), @JoinColumn(name="ordersuf")}
    //          )
    //@Transient
    //private Set<OrderLine> orderLines;

    //, joinColumns = {@JoinColumn(name="orderno")})
    
//    /**
//     * @return the orderNo
//     */
//    public int getOrderNo() {
//        return orderNo;
//    }
//
//    /**
//     * @param orderNo the orderNo to set
//     */
//    public void setOrderNo(int orderNo) {
//        this.orderNo = orderNo;
//    }
//
//    /**
//     * @return the orderSuf
//     */
//    public int getOrderSuf() {
//        return orderSuf;
//    }
//
//    /**
//     * @param orderSuf the orderSuf to set
//     */
//    public void setOrderSuf(int orderSuf) {
//        this.orderSuf = orderSuf;
//    }

    /**
     * @return the transType
     */
    public String getTransType() {
        return transType;
    }
    
    public String getTransTypeText() {
        if(transType.equalsIgnoreCase("SO"))
            return "Stock Order";        
        else if(transType.equalsIgnoreCase("QU"))
            return "Quote";
        else if(transType.equalsIgnoreCase("DO"))
            return "Direct Order";
        else if(transType.equalsIgnoreCase("RA"))
            return "Return";        
        else
            return transType;
    }

    /**
     * @param transType the transType to set
     */
    public void setTransType(String transType) {
        this.transType = transType;
    }

    /**
     * @return the custNo
     */
    public BigDecimal getCustNo() {
        return custNo;
    }

    /**
     * @param custNo the custNo to set
     */
    public void setCustNo(BigDecimal custNo) {
        this.custNo = custNo;
    }

    /**
     * @return the shipTo
     */
    public String getShipTo() {
        return shipTo;
    }

    /**
     * @param shipTo the shipTo to set
     */
    public void setShipTo(String shipTo) {
        this.shipTo = shipTo;
    }

    /**
     * @return the custPo
     */
    public String getCustPo() {
        return custPo;
    }

    /**
     * @param custPo the custPo to set
     */
    public void setCustPo(String custPo) {
        this.custPo = custPo;
    }

    /**
     * @return the enterDt
     */
    public Date getEnterDt() {
        return enterDt;
    }

    /**
     * @param enterDt the enterDt to set
     */
    public void setEnterDt(Date enterDt) {
        this.enterDt = enterDt;
    }

    /**
     * @return the invoiceDt
     */
    public Date getInvoiceDt() {
        return invoiceDt;
    }

    /**
     * @param invoiceDt the invoiceDt to set
     */
    public void setInvoiceDt(Date invoiceDt) {
        this.invoiceDt = invoiceDt;
    }

    /**
     * @return the totalOrderAmt
     */
    public BigDecimal getTotalOrderAmt() {
        return totalOrderAmt;
    }

    /**
     * @param totalOrderAmt the totalOrderAmt to set
     */
    public void setTotalOrderAmt(BigDecimal totalOrderAmt) {
        this.totalOrderAmt = totalOrderAmt;
    }

    /**
     * @return the stageCode
     */
    public int getStageCode() {
        return stageCode;
    }

    public String getStageText() {
        switch(stageCode) {
            case 0: return "Entered";
            case 1: return "Ordered";
            case 2: return "Picked";
            case 3: return "Shipped";
            case 4: return "Invoiced";
            case 5: return "Paid";
            case 9: return "Cancelled";
            default: return "Unknown";
        }
    }
    
    /**
     * @param stageCode the stageCode to set
     */
    public void setStageCode(int stageCode) {
        this.stageCode = stageCode;
    }

//    /**
//     * @return the cono
//     */
//    public int getCoNo() {
//        return coNo;
//    }
//
//    /**
//     * @param cono the cono to set
//     */
//    public void setCono(int coNo) {
//        this.coNo = coNo;
//    }

    /**
     * @return the whse
     */
    public String getWhse() {
        return whse;
    }

    /**
     * @param whse the whse to set
     */
    public void setWhse(String whse) {
        this.whse = whse;
    }

    /**
     * @return the shipVia
     */
    public String getShipVia() {
        return shipVia;
    }

    /**
     * @param shipVia the shipVia to set
     */
    public void setShipVia(String shipVia) {
        this.shipVia = shipVia;
    }

    /**
     * @return the reference
     */
    public String getReference() {
        return reference;
    }

    /**
     * @param reference the reference to set
     */
    public void setReference(String reference) {
        this.reference = reference;
    }

    /**
     * @return the instructions
     */
    public String getInstructions() {
        return instructions;
    }

    /**
     * @param instructions the instructions to set
     */
    public void setInstructions(String instructions) {
        this.instructions = instructions;
    }

    /**
     * @return the termsDesc
     */
    public String getTermsDesc() {
        return termsDesc;
    }

    /**
     * @param termsDesc the termsDesc to set
     */
    public void setTermsDesc(String termsDesc) {
        this.termsDesc = termsDesc;
    }

    /**
     * @return the shipDt
     */
    public Date getShipDt() {
        return shipDt;
    }

    /**
     * @param shipDt the shipDt to set
     */
    public void setShipDt(Date shipDt) {
        this.shipDt = shipDt;
    }

    /**
     * @return the subTotal
     */
    public BigDecimal getSubTotal() {
        return subTotal;
    }

    /**
     * @param subTotal the subTotal to set

src/main/java/com/kawauso/base/form/CartForm.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kawauso.base.form;

import com.kawauso.base.bean.Cart;

/**
 *
 * @author chris.weaver
 */
public class CartForm extends Cart
{
    private String step;
    private int shipMonth;
    private int shipDay;
    private int shipYear;

    /**
     * @return the shipMonth
     */
    public int getShipMonth() {
        return shipMonth;
    }

    /**
     * @param shipMonth the shipMonth to set
     */
    public void setShipMonth(int shipMonth) {
        this.shipMonth = shipMonth;
    }

    /**
     * @return the shipDay
     */
    public int getShipDay() {
        return shipDay;
    }

    /**
     * @param shipDay the shipDay to set
     */
    public void setShipDay(int shipDay) {
        this.shipDay = shipDay;
    }

    /**
     * @return the shipYear
     */
    public int getShipYear() {
        return shipYear;
    }

    /**
     * @param shipYear the shipYear to set
     */
    public void setShipYear(int shipYear) {
        this.shipYear = shipYear;
    }

    /**
     * @return the step
     */
    public String getStep() {
        return step;
    }

    /**
     * @param step the step to set
     */
    public void setStep(String step) {
        this.step = step;
    }
}

src/main/webapp/WEB-INF/jsp/cart/confirm.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="t" tagdir="/WEB-INF/tags" %>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<%@taglib uri="/WEB-INF/kawauso-utils.tld" prefix="util"%>

<t:layout>
    <jsp:body>

<div class="section" style="width:100%;">
    <div class="left">
        <h2>Order Confirmation ${results.orderDetails.orderNo}-<c:if test="${results.orderDetails.orderSuf < 10}">0</c:if>${results.orderDetails.orderSuf}</h2>
    </div>

    <div class="follow-sprite follow-sprite-active left" style="margin-top:9px">
        <a href="#" style="height:22px; display:block;" title="Click to follow"></a>
    </div>
</div>

<c:if test="${not empty message}">
<div class="section" style="width:100%; padding-bottom:10px;">
    <img src="https://s3.amazonaws.com/mgl1939/img/red_error.png" border="0" style="width:32px; vertical-align:middle"> ${message}
</div>
</c:if>

<div id="details-main" class="container border">    
    <h2 class="header active">Order Information</h2>
    <div class="section" style="line-height: 1.5em;">
        <div class="half">
            <dl>
                <dt>Status:</dt><dd>${results.orderDetails.stageText}&nbsp;</dd>
                <dt>Order Date:</dt><dd><fmt:formatDate pattern="MM/dd/yyyy" value="${results.orderDetails.enterDt}"/>&nbsp;</dd>
                <dt>Request Date:</dt><dd><fmt:formatDate pattern="MM/dd/yyyy" value="${results.orderDetails.reqShipDt}"/>&nbsp;</dd>
                <dt>Ship Date:</dt><dd><fmt:formatDate pattern="MM/dd/yyyy" value="${results.orderDetails.reqShipDt}"/>&nbsp;</dd>
                <dt>Ship Via:</dt><dd>${results.orderDetails.shipVia}&nbsp;</dd>
                <dt>Terms:</dt><dd>${results.orderDetails.termsDesc}&nbsp;</dd>
                <dt>PO #:</dt><dd>${results.orderDetails.custPo}&nbsp;</dd>
                <dt>Warehouse:</dt><dd>${results.orderDetails.whse}&nbsp;</dd>
                <dt>Reference:</dt><dd>${results.orderDetails.reference}&nbsp;</dd>
                <dt>Instructions:</dt><dd>${results.orderDetails.instructions}&nbsp;</dd>
            </dl>
            <br/>
        </div>
        <div class="half">
            <dl>
            <b>Bill To Address:</b><br/>
            ${results.orderDetails.shipToName}<br/>
            ${results.orderDetails.shipToAddr1}<br/>
            ${results.orderDetails.shipToAddr2}<br/>
            ${results.orderDetails.shipToCity}, ${results.orderDetails.shipToState} ${results.orderDetails.shipToZip}<br/>
            <br/>
            <b>Ship To Address:</b><br/>
            ${results.orderDetails.shipToName}<br/>
            ${results.orderDetails.shipToAddr1}<br/>
            ${results.orderDetails.shipToAddr2}<br/>
            ${results.orderDetails.shipToCity}, ${results.orderDetails.shipToState} ${results.orderDetails.shipToZip}<br/>
            </dl>
        </div>
    </div>
</div>
<br/>

<div class="fake-table">
    <div class="header">
        <div class="row">
            <div class="cell">Product</div>
            <div class="cell txt-center">Qty Ordered</div>
            <div class="cell txt-center">Qty Shipped</div>
            <div class="cell txt-right">Price</div>
            <div class="cell txt-right">Ext. Price</div>
        </div>
    </div>
    <div class="body">
        <c:forEach items="${results.orderDetails.orderLines}" var="line" varStatus="itemStatus">
        <div class="row">
            <div class="cell">
                <a href="<c:url value="/product/detail.htm?prod=${util:base64Encode(line.shipProd)}"/>">${line.description}</a><br/>
               <b>SKU:</b> ${line.shipProd}
            </div>
            <div class="cell txt-center"><span class="narrow">Quantity Ordered</span> ${line.qtyOrder}</div>
            <div class="cell txt-center"><span class="narrow">Quantity Shipped:</span> ${line.qtyShip}</div>
            <div class="cell txt-right"><span class="narrow">Price:</span>
                <fmt:formatNumber value="${line.price}" type="currency" currencySymbol="$" pattern="¤#,##0.00;¤-#,##0.00"/>
            </div>
            <div class="cell txt-right"><span class="narrow">Ext. Price:</span>
                <fmt:formatNumber value="${line.netAmount}" type="currency" currencySymbol="$" pattern="¤#,##0.00;¤-#,##0.00"/>
            </div>
        </div>
        </c:forEach>
    </div>
</div>
<br/>

<div class="right" style="padding-right:5px;">
    Sub Total: <fmt:formatNumber value="${results.orderDetails.subTotal}" type="currency" currencySymbol="$" pattern="¤#,##0.00;¤-#,##0.00"/><br/>
    Taxes: <fmt:formatNumber value="${results.orderDetails.taxAmount}" type="currency" currencySymbol="$" pattern="¤#,##0.00;¤-#,##0.00"/><br/><br/>
    <b>Order Total: <fmt:formatNumber value="${results.orderDetails.invAmount}" type="currency" currencySymbol="$" pattern="¤#,##0.00;¤-#,##0.00"/></b>
</div>
<br/><br/>

    </jsp:body>
</t:layout>

src/main/webapp/WEB-INF/jsp/cart/index.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="t" tagdir="/WEB-INF/tags" %>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn"%>
<%@taglib uri="/WEB-INF/kawauso-utils.tld" prefix="util"%>

<t:layout>
  <jsp:body>

<script type="text/javascript" src="http://jquery.iceburg.net/jqModal/jqModal.js"></script>      
      
<script>
$(function() {
    $(".removeCartItem").on("click", function () {
        $.post("/web/cart/index.htm",
            { productCode: $(this).data('val'), quantity: 0 },
            function(data) {
                window.location.reload();
            }
        );
    });   

    $('#modalSaveCart').on('click', function(e) {
        e.preventDefault();

        $.ajax({
            url: '/web/user/lists/new-from-cart.htm',
            beforeSend: function() {
                $('#dialog').jqm({overlay: 60});
                $('.jqmWindow').html('<br/><br/><br/><center><img src="http://www.4metal.pl/images/wait_animation.gif"/><br/>Loading...</center><br/><br/><br/>');
                $('#dialog').jqmShow();
            },
            success: function(res) {
                $('.jqmWindow').html(res);
            }
        });
    });    
    
    $('#modalClearCart').on('click', function(e) {
        e.preventDefault();
        
        window.scrollTo(0, 0);

        $.ajax({
            url: '/web/cart/clear.htm',
            beforeSend: function() {
                $('#dialog').jqm({overlay: 60});
                $('.jqmWindow').html('<br/><br/><br/><center><img src="http://www.4metal.pl/images/wait_animation.gif"/><br/>Loading...</center><br/><br/><br/>');
                $('#dialog').jqmShow();
            },
            success: function(res) {
                $('.jqmWindow').html(res);
            }
        });
    });     
});
</script>      

<h2>Shopping Cart</h2>

<c:if test="${not empty message}">
    <img src="http://www.familyfirstalerts.com/alert-images/emergency-alert-system.gif" border="0" style="width:32px; height:32px; vertical-align:middle"/>
    <span style="font-size:125%;">${message}</span><br/><br/>
</c:if>

<c:choose>
<c:when test="${fn:length(items) > 0}">
<table border='0' cellspacing="0" cellpadding="0" style="width:100%">
    <tr>
        <td style="padding-bottom:8px;">
            <a id="modalSaveCart" class="ui-button" href="/web">Save to a List</a>
        </td>
        <td style="padding-bottom:8px; text-align:right;">
                           <a href="/web/index.htm"><span class="shutdownLink">Button disabled – click for more information</span></a>
            <a class="ui-link-button disabled" href="<c:url value="/cart/checkout.htm"/>">Checkout</a>
        </td>
    </tr>
</table>    
          
<div class="fake-table">
    <div class="header">
        <div class="row">
            <div class="cell"></div>
            <div class="cell">Product</div>
            <div class="cell"><div class="center">Quantity</div></div>
            <div class="cell"><div class="right">Price</div></div>
            <div class="cell"><div class="right">Total Price</div></div>
        </div>
    </div>
    <div class="body">            
        <c:forEach var="item" items="${items}">
        <div class="row">
            <div class="cell">
                <div class="center">
                    <c:choose>
                    <c:when test="${not empty item.productDetail.image}">
                    <img src="http://mgl1939.s3-website-us-east-1.amazonaws.com/products/tn70/tn70_${item.productDetail.image}"/>
                    </c:when>
                    <c:otherwise>
                    <img src="http://www.adpeso.de/wp-content/uploads/2013/08/camera-icon-256.png" width="70" height="70"/>
                    </c:otherwise>
                    </c:choose>
                </div>
            </div>            
            <div class="cell">
                <a href="<c:url value="/product/detail.htm?prod=${util:base64Encode(item.productCode)}"/>" class="prod-link">${item.productDetail.description}</a><br/>
                <b>SKU:</b> ${item.productDetail.product}<br/>
                <b>Manufacturer:</b> 
            </div>
            <div class="cell">
                <div class="center">
                    <form action="/web/cart/index.htm" method="post">
                        <input type="hidden" name="productCode" value="${util:base64Encode(item.productCode)}"/>
                        <input type="text" class="qty" name="quantity" onchange="this.form.submit()" style="width:50px; text-align:right; padding-right:8px;" value="${item.qty}"><br/>
                        <div class="removeCartItem fakeLink" data-val="${util:base64Encode(item.productCode)}">Remove</div>
                    </form>
                </div>
            </div>
            <div class="cell">
                <div class="right">
                    <span class="narrow">Your Price:</span>
                    <fmt:formatNumber value="${item.unitPrice}" type="currency" currencySymbol="$" pattern="¤#,##0.00;¤-#,##0.00"/>
                </div>
            </div>
            <div class="cell">
                <div class="right">
                    <span class="narrow">Extended Price:</span>
                    <fmt:formatNumber value="${item.qty * item.unitPrice}" type="currency" currencySymbol="$" pattern="¤#,##0.00;¤-#,##0.00"/>
                </div>
            </div>            
        </div>
        </c:forEach>
    </div>
</div>

<table border='0' cellspacing="0" cellpadding="0" style="width:100%">
    <tr>
        <td colspan="2" style="padding:8px; text-align:right;"><b>Order Total: <fmt:formatNumber value="${subTotal}" type="currency" currencySymbol="$" pattern="¤#,##0.00;¤-#,##0.00"/></b></td>
    </tr>
    <tr>
        <td style="padding-top:8px;">
            <a id="modalClearCart" class="ui-button" href="/web" data-value="32">Clear Cart</a>
        </td>
        <td style="padding-top:8px; text-align:right;">
        <a href="/web/index.htm"><span class="shutdownLink">Button disabled – click for more information</span></a>
            <a class="ui-link-button disabled" href="<c:url value="/cart/checkout.htm"/>" disabled>Checkout</a>
        </td>
    </tr>
</table>    
</div>
</c:when>
<c:otherwise>
<div style="font-size:125%; padding:20px;">
    <img src="https://s3.amazonaws.com/mgl1939/img/red_error.png" style="width:32px; vertical-align:middle;">
    Your cart is empty.
    <br/><br/><br/><br/><br/><br/>
</div>
</c:otherwise>
</c:choose>

  </jsp:body>
</t:layout>
<style>
a.disabled {
  pointer-events: none;
  cursor: default;
}
.shutdownLink {
        color: #f44248;
        text-decoration: underline;
    	} 
</style>

src/main/webapp/WEB-INF/jsp/cart/review.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="t" tagdir="/WEB-INF/tags" %>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@taglib uri="/WEB-INF/kawauso-utils.tld" prefix="util"%>

<t:layout>
    <jsp:body>

<h2>Step 2: Review Order</h2>

<div id="details-main" class="container border">    
    <h2 class="header active">Order Information</h2>
    <div class="section pad10" style="line-height: 1.5em;">
        <div class="half">
            <div style="padding: 6px 15px;">
            <b>Bill To Address:</b><br/>
            ${accountInfo.name}<br/>
            ${accountInfo.address1}<br/>
            ${accountInfo.city}, ${accountInfo.state} ${accountInfo.zip}<br/>
            <br/>
            <b>Ship To Address:</b><br/>
            ${cartForm.shipToName}<br/>
            ${cartForm.shipToAddr1}<br/>
            ${cartForm.shipToAddr2}<br/>
            ${cartForm.shipToCity}, ${cartForm.shipToState} ${cartForm.shipToZip}<br/><br/>
            </div>
        </div>
        
        <div class="half">
            <dl>
                <dt>Bill to Account:</dt><dd>${cartForm.jobId}&nbsp;</dd>
                <dt>Purchase Order:</dt><dd>${cartForm.custPo}&nbsp;</dd>
                <dt>Warehouse:</dt><dd>${currentLocation.whseName} (${session.warehouse}) <%--${cartForm.shipWhseId}--%>&nbsp;</dd>
                <dt>Ship Date:</dt><dd>${cartForm.shipDate}&nbsp;</dd>
                <dt>Ship Via:</dt><dd>${cartForm.shipVia}&nbsp;</dd>
                <dt>Reference:</dt><dd>${cartForm.reference}&nbsp;</dd>
                <dt>Instructions:</dt><dd>${cartForm.instructions}&nbsp;</dd>
            </dl>
            <br/>
        </div>

    </div>
</div>
<br/>

<form:form method="POST" commandName="cartForm" action="/web/cart/checkout.htm" onSubmit="document.getElementById('submit').disabled=true;">    
<form:input type="hidden" path="step" value="commit"/>
<div class="fake-table">
    <div class="header">
        <div class="row">
            <div class="cell"></div>
            <div class="cell">Product</div>
            <div class="cell"><div class="center">Order Qty</div></div>
            <div class="cell"><div class="center">Qty Avail</div></div>
            <div class="cell"><div class="right">Price</div></div>
            <div class="cell"><div class="right">Ext. Price</div></div>
        </div>
    </div>
    <div class="body">
        <c:forEach var="line" items="${cartLines}" varStatus="itemStatus">
        <div class="row">
            <div class="cell">
                <c:choose>
                <c:when test="${not empty line.productDetail.image}">
                    <img src="http://mgl1939.s3-website-us-east-1.amazonaws.com/products/tn70/tn70_${line.productDetail.image}">
                </c:when>
                <c:otherwise>
                    <img src="//mgl1939.s3-website-us-east-1.amazonaws.com/img/camera-icon-256.png" width="70" height="70">
                </c:otherwise>
                </c:choose>
            </div>
            <div class="cell">
                <a href="<c:url value="/product/detail.htm?prod=${util:base64Encode(line.productDetail.product)}"/>" style="font-size:125%">${line.productDetail.description}</a><br/>
                <c:if test="${not empty line.productDetail.userDescription}">
                    <b>My Description: </b>${line.productDetail.userDescription}<br/>
                </c:if>

                <b>SKU: </b>${line.productDetail.product}<br/>

            </div>
            <div class="cell">
                <div class="center">
                    <span class="mobile-only">Order Qty: </span>${line.qty}
                </div>
            </div>
            <div class="cell">
                <div class="center">
                    <span class="mobile-only">Qty Avail: </span>${line.productDetail.avail}
                    <span class="mobile-only">
                    <c:if test="${line.productDetail.avail - line.qty < 0}">
                        Backordered: ${(line.productDetail.avail - line.qty) * -1}
                    </c:if>
                    </span>
                </div>
            </div>
            <div class="cell">
                <div class="right">
                    <span class="mobile-only">Price: </span>
                    <fmt:formatNumber value="${line.unitPrice}" type="currency" currencySymbol="$" pattern="¤#,##0.00;¤-#,##0.00"/> 
                </div>
            </div>
            <div class="cell" style="white-space:nowrap;">
                <div class="right">
                <span class="mobile-only">Ext Price: </span>
                <fmt:formatNumber value="${line.qty * line.unitPrice}" type="currency" currencySymbol="$" pattern="¤#,##0.00;¤-#,##0.00"/> 
                </div>
            </div>
        </div>
        </c:forEach>
    </div>
</div>
<br/>

<div class="right" style="padding-right:5px;">
<b>Order Total: <fmt:formatNumber value="${subTotal}" type="currency" currencySymbol="$" pattern="¤#,##0.00;¤-#,##0.00"/></b>
</div><br/><br/>

<div class="section">
    <div class="right">
    <a href="/web/index.htm"><span class="shutdownLink">Button disabled – click for more information</span></a>
        <input type="submit" id="submit" value="Place Order" disabled/>
    </div>
</div>
<br/>


</form:form>
        
    </jsp:body>
</t:layout>

<style>
a.disabled {
  pointer-events: none;
  cursor: default;
}
.shutdownLink {
        color: #f44248;
        text-decoration: underline;
    	} 
</style>